export {
  RATING_SCALE,
  RESOURCE_SCALE,
  RESOURCE_SCALE_LEGEND,
  ADDABLE_FIELD_TYPES,
  SECTION_BRANCHING_FIELD,
  SECTION_QUESTION_FIELD_TYPES,
  FIELD_TYPES,
  fieldNeedsOptions,
  fieldTypeMeta,
  getFieldType,
  minOptionsForType,
  parseFieldAnswer,
  parseOptionList,
  getChoiceList,
  getAllowOther,
  getMaxLength,
  buildChoiceOptions,
  buildTextOptions,
  buildQuestionLogic,
  collectStepAnswer,
  isQuestionVisible,
  parseQuestionLogic,
  type FieldTypeValue,
  type QuestionLogic,
} from "@/lib/field-types";
