-- Date picker field type
ALTER TABLE `Question` MODIFY `type` ENUM('SHORT_TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DROPDOWN', 'COMMENT', 'SUGGESTION', 'RATING', 'RESOURCE_RATING', 'YES_NO', 'SECTION', 'DATE') NOT NULL;
ALTER TABLE `FormTemplateQuestion` MODIFY `type` ENUM('SHORT_TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DROPDOWN', 'COMMENT', 'SUGGESTION', 'RATING', 'RESOURCE_RATING', 'YES_NO', 'SECTION', 'DATE') NOT NULL;
