-- Section branching dropdown + explicit section option link
ALTER TABLE `FormSection` ADD COLUMN `branchValue` VARCHAR(191) NULL;
ALTER TABLE `FormTemplateSection` ADD COLUMN `branchValue` VARCHAR(191) NULL;

ALTER TABLE `Question` MODIFY `type` ENUM('SHORT_TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DROPDOWN', 'COMMENT', 'SUGGESTION', 'RATING', 'RESOURCE_RATING', 'YES_NO', 'DATE', 'BRANCHING_DROPDOWN') NOT NULL;
ALTER TABLE `FormTemplateQuestion` MODIFY `type` ENUM('SHORT_TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DROPDOWN', 'COMMENT', 'SUGGESTION', 'RATING', 'RESOURCE_RATING', 'YES_NO', 'DATE', 'BRANCHING_DROPDOWN') NOT NULL;
